// Catálogo de Combis y Minibuses más populares en Argentina con especificaciones técnicas y 3D

export const ARGENTINA_VEHICLE_CATALOG = [
  {
    id: 'MERCEDES_SPRINTER',
    brand: 'Mercedes-Benz',
    model: 'Sprinter 516 CDI Minibús',
    type: 'MINIBUS',
    capacity: 20,
    seatCount: 20,
    luggage: 'LARGE',
    approxCargoKg: 850,
    yearDefault: 2024,
    description: 'El referente indiscutido en transporte corporativo, charters y servicios ejecutivos en Argentina. Techo elevado, ventanillas panorámicas y confort premium.',
    badge: 'Más Elegida en Argentina',
    colorDefault: 'Blanco Ártico',
    geom: {
      length: 6.8,
      width: 2.2,
      height: 2.7,
      hoodLength: 1.3,
      hoodSlope: 0.35,
      roofCurve: 0.25,
      grilleType: 'MERCEDES_STAR',
      windowRows: 4,
      seatRows: 5,
      dualRearWheels: false,
      headlightStyle: 'SPRINTER_LED'
    }
  },
  {
    id: 'RENAULT_MASTER',
    brand: 'Renault',
    model: 'Master L3H2 Minibús',
    type: 'MINIBUS',
    capacity: 16,
    seatCount: 16,
    luggage: 'MEDIUM',
    approxCargoKg: 650,
    yearDefault: 2024,
    description: 'Combi moderna y ágil muy utilizada para traslados urbanos y corporativos. Trompa robusta con rombo cromado y gran visibilidad.',
    badge: 'Combi Ejecutiva',
    colorDefault: 'Gris Plata Metalizado',
    geom: {
      length: 6.2,
      width: 2.15,
      height: 2.55,
      hoodLength: 1.1,
      hoodSlope: 0.3,
      roofCurve: 0.2,
      grilleType: 'RENAULT_DIAMOND',
      windowRows: 3,
      seatRows: 4,
      dualRearWheels: false,
      headlightStyle: 'MASTER_ANGLED'
    }
  },
  {
    id: 'IVECO_DAILY',
    brand: 'Iveco',
    model: 'Daily 70C17 Minibús',
    type: 'MINIBUS',
    capacity: 24,
    seatCount: 24,
    luggage: 'LARGE',
    approxCargoKg: 1100,
    yearDefault: 2025,
    description: 'Minibús de gran porte y máxima capacidad. Chasis reforzado con doble rueda trasera para turismo y media distancia.',
    badge: 'Máxima Capacidad (24 Pasajeros)',
    colorDefault: 'Blanco Ártico',
    geom: {
      length: 7.4,
      width: 2.3,
      height: 2.85,
      hoodLength: 1.45,
      hoodSlope: 0.28,
      roofCurve: 0.28,
      grilleType: 'IVECO_BOLD',
      windowRows: 5,
      seatRows: 6,
      dualRearWheels: true,
      headlightStyle: 'IVECO_DUAL'
    }
  },
  {
    id: 'FORD_TRANSIT',
    brand: 'Ford',
    model: 'Transit Minibús 17+1',
    type: 'MINIBUS',
    capacity: 18,
    seatCount: 18,
    luggage: 'MEDIUM',
    approxCargoKg: 700,
    yearDefault: 2024,
    description: 'Líneas aerodinámicas elegantes, tecnología Kinetic Design y óptimo rendimiento para traslados diarios.',
    badge: 'Gran Rendimiento',
    colorDefault: 'Azul Noche Metalizado',
    geom: {
      length: 6.4,
      width: 2.2,
      height: 2.6,
      hoodLength: 1.25,
      hoodSlope: 0.38,
      roofCurve: 0.22,
      grilleType: 'FORD_HEX',
      windowRows: 4,
      seatRows: 4,
      dualRearWheels: false,
      headlightStyle: 'TRANSIT_SWEPT'
    }
  },
  {
    id: 'TOYOTA_HIACE',
    brand: 'Toyota',
    model: 'Hiace Commuter VIP',
    type: 'VAN',
    capacity: 14,
    seatCount: 14,
    luggage: 'LIGHT',
    approxCargoKg: 500,
    yearDefault: 2024,
    description: 'Van ejecutiva japonesa de alta gama. Máxima insonorización, confiabilidad mecánica y confort para servicios premium.',
    badge: 'Gama Premium VIP',
    colorDefault: 'Gris Grafito',
    geom: {
      length: 5.9,
      width: 2.05,
      height: 2.45,
      hoodLength: 0.95,
      hoodSlope: 0.45,
      roofCurve: 0.16,
      grilleType: 'TOYOTA_BAR',
      windowRows: 3,
      seatRows: 3,
      dualRearWheels: false,
      headlightStyle: 'HIACE_SLEEK'
    }
  },
  {
    id: 'PEUGEOT_BOXER',
    brand: 'Peugeot',
    model: 'Boxer Maxi Combi',
    type: 'COMBI',
    capacity: 16,
    seatCount: 16,
    luggage: 'MEDIUM',
    approxCargoKg: 650,
    yearDefault: 2023,
    description: 'Combi de piso bajo, amplia boca de acceso y gran espacio para traslados y charters.',
    badge: 'Clásica y Confiable',
    colorDefault: 'Blanco Ártico',
    geom: {
      length: 6.1,
      width: 2.2,
      height: 2.5,
      hoodLength: 1.05,
      hoodSlope: 0.32,
      roofCurve: 0.18,
      grilleType: 'PEUGEOT_LION',
      windowRows: 3,
      seatRows: 4,
      dualRearWheels: false,
      headlightStyle: 'BOXER_HIGH'
    }
  }
];

export const ARGENTINA_COLORS = [
  { name: 'Blanco Ártico', hex: '#f8fafc', textColor: '#0f172a', desc: 'Color institucional estándar' },
  { name: 'Gris Plata Metalizado', hex: '#94a3b8', textColor: '#0f172a', desc: 'Acabado metalizado elegante' },
  { name: 'Gris Grafito', hex: '#475569', textColor: '#ffffff', desc: 'Tono corporativo sobrio' },
  { name: 'Negro Obsidiana', hex: '#1e293b', textColor: '#ffffff', desc: 'Línea ejecutiva VIP' },
  { name: 'Azul Noche Metalizado', hex: '#1e3a8a', textColor: '#ffffff', desc: 'Flota interurbana premium' },
  { name: 'Rojo Granate', hex: '#991b1b', textColor: '#ffffff', desc: 'Servicios turísticos' },
  { name: 'Champagne Ejecutivo', hex: '#d97706', textColor: '#0f172a', desc: 'Acabado exclusivo' }
];
